#!/bin/sh

menu='rofi -show -dmenu -p'
rofiUsed=1
player=vlc
numpages=1
webtorrentNotFound=0
baseurl="https://1337x.to"
cachedir="$HOME/.cache/notflix"
notify=notify-send

setup() {
  mkdir -p $cachedir
}

cleanup() {
  rm -rf $cachedir
}

isInstalled() {
	which "$1" 2>/dev/null>&2
}

command -v "rofi" 2>/dev/null>&2 || rofiUsed=0 # dmenu is used if rofi is not found
command -v "vlc" 2>/dev/null>&2 || player=mpv # mpv is used if vlc is not found
command -v "notify-send" 2>/dev/null>&2 || notify=echo # use terminal to display messages if libnotify-dev is not found
command -v "webtorrent" || webtorrentNotFound=1
setup

if [ $webtorrentNotFound -gt 0 ]; then
  $notify "notflix: could not find webtorrent."
  exit 1
fi

if [ -z $1 ]; then
  if [ $rofiUsed -lt 1 ]; then
    query=$(dmenu -p "search: " <&-)
    menu="dmenu -i -l 25"
  else
    query=$($menu "search")
    menu+=" select"
  fi
else
  query=$1
fi

# format query
query="$(echo $query | sed 's/ /+/g')"

# cache query from 1337x
curl -s $baseurl/search/$query/$numpages/ > $cachedir/tmp.html

# grep titles
grep -o '<a href="/torrent/.*</a>' $cachedir/tmp.html |
  sed 's/<[^>]*>//g' > $cachedir/titles.bw

# check amount of magnets found
result_count=$(wc -l $cachedir/titles.bw | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  $notify "notflix: no result found."
  exit 2
fi

# get seeders and leechers for each magnet
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' $cachedir/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > $cachedir/seedleech.bw

# get disk size of torrent
grep -o '<td class="coll-4 size.*</td>' $cachedir/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > $cachedir/size.bw

# get magnet links
grep -E '/torrent/' $cachedir/tmp.html |
  sed -E 's#.*(/torrent/.*)/">.*/#\1#' |
  sed 's/td>//g' > $cachedir/links.bw

# clear up data to display
sed 's/\./ /g; s/\-/ /g' $cachedir/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > $cachedir/tmp && mv $cachedir/tmp $cachedir/titles.bw

awk '{print NR " - ["$0"]"}' $cachedir/size.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/size.bw
awk '{print "[S:"$1 ", L:"$2"]" }' $cachedir/seedleech.bw > $cachedir/tmp && mv $cachedir/tmp $cachedir/seedleech.bw

# Getting the line number
LINE=$(paste -d\   $cachedir/size.bw $cachedir/seedleech.bw $cachedir/titles.bw |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')

if [ -z "$LINE" ]; then
  exit 0
fi

url=$(head -n $LINE $cachedir/links.bw | tail -n +$LINE)
fullURL="${baseurl}${url}/"

# Requesting page for magnet link
curl -s $fullURL > $cachedir/tmp.html
magnet=$(grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" $cachedir/tmp.html | head -n 1) 

$notify "notflix: launching webtorrent."
cleanup
webtorrent "$magnet" --$player 

